# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Spatial_Analysis_Agent
                                 A QGIS plugin
 A plugin integration between QGIS and Large Language Model (LLM) for Spatial Analysis
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-08-12
        copyright            : (C) 2024 by GIBD
        email                : teakinboyewa@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Spatial_Analysis_Agent class from file Spatial_Analysis_Agent.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .SpatialAnalysisAgent import SpatialAnalysisAgent
    return SpatialAnalysisAgent(iface)
